### PR TITLE
Introducing Multi-Path DMA Support for mlx5 RDMA Driver

### PR DESCRIPTION
**Pull request by tdavenvidia**
This patch series cherry-pick/backport multipath-DMA Support patch series from upstream, https://lore.kernel.org/all/cover.1722512548.git.leon@kernel.org/

### CODE REVIEW

**Review by jamieNguyenNVIDIA — CHANGES_REQUESTED** [review]
Can you add backport/cherry-pick information to each commit?

Something like:
`(cherry picked from commit #### linux)`
or
`(backported from commit #### linux)`


From what I can tell:
(1/8) picked cleanly
(2/8) picked cleanly
(3/8) did not pick cleanly, but backport looked straightforward
(4/8) picked cleanly
(5/8) picked cleanly
(6/8) picked cleanly
(7/8) did not pick cleanly, but backport seemed okay despite the large commit
(8/8) picked cleanly

The patches themselves look good outside of the missing cherry-pick/backport information.

**Comment by clsotog** [comment]
The patches looks ok for me.

**Comment by clsotog** [comment]
For me this looks ok

**Comment by tdavenvidia** [comment]
@jamieNguyenNVIDIA

Added cherry-pick/backported info.

**Comment by nvmochs** [comment]
I confirmed Jamie's assessment, verified that there are no upstream fixes for these commits, and that the SHAs in the pick tags matches upstream.

Acked-by: Matthew R. Ochs <mochs@nvidia.com>

**Review by jamieNguyenNVIDIA — COMMENTED** [review]
It looks like all of these are in Torvalds' tree now, so I would call out those commits instead of the `rdma/for-next` ones:

```
ec7ad6530909 RDMA/mlx5: Introduce GET_DATA_DIRECT_SYSFS_PATH ioctl
de8f847a5114 RDMA/mlx5: Add support for DMABUF MR registrations with Data-direct
3aa73c6b795b RDMA: Pass uverbs_attr_bundle as part of '.reg_user_mr_dmabuf' API
253c61dc256b RDMA/umem: Introduce an option to revoke DMABUF umem
682358fd35de RDMA/umem: Add support for creating pinned DMABUF umem with a given dma device
2e8e631d7a41 RDMA/mlx5: Add the initialization flow to utilize the 'data direct' device
6910e3660d86 RDMA/mlx5: Introduce the 'data direct' driver
a18eb864019e Introducing Multi-Path DMA Support for mlx5 RDMA Driver
...
c772a2c69018 net/mlx5: Add IFC related stuff for data direct
```

EDIT: the commit SHAs seem to match the ones in Torvalds' tree, so I think it's just a matter of `s/rdma:for-next/linux/g`.

**Review by nvmochs — APPROVED** [review]

**Comment by tdavenvidia** [comment]
@jamieNguyenNVIDIA

IMO 's/rdma:for-next/linux/g'  is really not needed, but I am doing it now :)

**Review by jamieNguyenNVIDIA — APPROVED** [review]

**Review by clsotog — APPROVED** [review]
Acked-by: Carol L Soto csoto@nvidia.com

**Comment by jamieNguyenNVIDIA** [comment]
Acked-by: Jamie Nguyen <jamien@nvidia.com>

(Not sure if you still needed mine since Carol gave hers above)

**Comment by KobaKoNvidia** [comment]
test

**Comment by nvmochs** [comment]
These were merged in via:
add7f35c1582 (tag: linux-nvidia-adv-6.8.0-1003.3) UBUNTU: linux-nvidia-adv-6.8.0-1003.3

**Pull request closed without merging**
