### PR TITLE
Integrate v6.8_ghvirt patches into tech-preview branch

### PR DESCRIPTION
**Pull request by nvmochs**
Pick the I/O virtualization content from the [6.8_ghvirt branch](https://github.com/NVIDIA/NV-Kernels/tree/6.8_ghvirt) to linux-nvidia-adv-6.8-next for inclusion in the tech preview kernel. Built .debs for x86 and arm64. Boot tested on x86 VM and ran GPU passthrough tests on Grace CG1.

### CODE REVIEW

**Comment by khfeng** [comment]
Hi Matt,

I wrote a simple script to find fixing commits in upstream, and here are the ones it found:
```
Fix found: 98db56e4900837e4d5d3892b332dca76c8c9f68a iommu/arm-smmu: Un-demote unhandled-fault msg
 for d525b0af0c3b8275e6f83fa0c0640338ed90661a iommu/arm-smmu: Pretty-print context fault related regs
Fix found: 0b4eeee2876f2b08442eb32081451bf130e01a4c iommu/arm-smmu-qcom: Register the TBU driver in qcom_smmu_impl_init
 for 414ecb030870a31262e5fd29fd372ee73b32a6be iommu/arm-smmu-qcom-debug: Add support for TBUs
Fix found: af048ec9c05178206e845a88bfd3cb2884a43da7 iommu/arm-smmu-v3: Fix a NULL vs IS_ERR() check
 for 52acd7d8a4130ad4dda6540dbbb821a92e1c0138 iommu/arm-smmu-v3: Add support for domain_alloc_user fn
Fix found: b58b133e680b20d219940e0fdb6f6132c2b60f38 iommu: Handle iommu faults for a bad iopf setup
 for 3dfa64aecbafc288216b2790438d395add192c30 iommu: Make iommu_report_device_fault() return void
Fix found: 79ea4a496ab5c970a3a793d863ed8893b1af107c iommufd/selftest: Fix buffer read overrrun in the dirty test
 for 9560393b830b415b2151b3dd8e065257cccbffa7 iommufd/selftest: Fix iommufd_test_dirty() to handle <u8 bitmaps
```

I think those should be included too. (Maybe skip the qcom one).

**Comment by kobak2026** [comment]
@nvmochs checked all commits have [cherry picked| backported]  
Most patches are still very similar with the original patches.  
There's one commit, I think it should be tagged as [backported from]  
there're more changes compared to original.  
```
31db5df6fc113e440fda2e6b7af3ebc887006c2a iommu/sva: Restore SVA handle sharing
```

**Comment by nvmochs** [comment]
> Hi Matt,
> 
> I wrote a simple script to find fixing commits in upstream, and here are the ones it found:
> 
> ```
> Fix found: 98db56e4900837e4d5d3892b332dca76c8c9f68a iommu/arm-smmu: Un-demote unhandled-fault msg
>  for d525b0af0c3b8275e6f83fa0c0640338ed90661a iommu/arm-smmu: Pretty-print context fault related regs
> Fix found: 0b4eeee2876f2b08442eb32081451bf130e01a4c iommu/arm-smmu-qcom: Register the TBU driver in qcom_smmu_impl_init
>  for 414ecb030870a31262e5fd29fd372ee73b32a6be iommu/arm-smmu-qcom-debug: Add support for TBUs
> Fix found: af048ec9c05178206e845a88bfd3cb2884a43da7 iommu/arm-smmu-v3: Fix a NULL vs IS_ERR() check
>  for 52acd7d8a4130ad4dda6540dbbb821a92e1c0138 iommu/arm-smmu-v3: Add support for domain_alloc_user fn
> Fix found: b58b133e680b20d219940e0fdb6f6132c2b60f38 iommu: Handle iommu faults for a bad iopf setup
>  for 3dfa64aecbafc288216b2790438d395add192c30 iommu: Make iommu_report_device_fault() return void
> Fix found: 79ea4a496ab5c970a3a793d863ed8893b1af107c iommufd/selftest: Fix buffer read overrrun in the dirty test
>  for 9560393b830b415b2151b3dd8e065257cccbffa7 iommufd/selftest: Fix iommufd_test_dirty() to handle <u8 bitmaps
> ```
> 
> I think those should be included too. (Maybe skip the qcom one).

Thanks for catching these. The "iommu: Handle iommu faults for a bad iopf setup" did not pick cleanly and required a minor context fixup. I added them in under the "Apply upstream patches for dependencies" cover letter and tested with the updated branch.

**Comment by nvmochs** [comment]
> @nvmochs checked all commits have [cherry picked| backported] Most patches are still very similar with the original patches. There's one commit, I think it should be tagged as [backported from] there're more changes compared to original.
> 
> ```
> 31db5df6fc113e440fda2e6b7af3ebc887006c2a iommu/sva: Restore SVA handle sharing
> ```

That patch and '45297d74c299 iommu/sva: Fix SVA handle sharing in multi device case' were already present in the base from Canonical, which is why they look "minimized" when picked the second time. I had determined this when originally creating this branch and decided to keep them for easier comparison with the source branch I range picked from (6.8_ghvirt). However, given that this may add to confusion about why they are present twice, I went ahead and rebased to remove the second picks. I confirmed that the source file (drivers/iommu/iommu-sva.c) remained the same before and after the rebase.

**Comment by nvmochs** [comment]
@KobaKoNvidia @khfeng I just pushed the updated branch with the changes described above (picked upstream fixes and removed commits that were already present in the base).

**Comment by khfeng** [comment]
Acked-by: Kai-Heng Feng <kaihengf@nvidia.com>

There are some new fixes in linux-next, but those can be picked up later once they are in mainline.

**Review by khfeng — APPROVED** [review]

**Comment by kobak2026** [comment]
Acked-by: Koba Ko <kobak@nvidia.com>

**Review by kobak2026 — APPROVED** [review]

**Comment by nvmochs** [comment]
These were merged in via:
add7f35c1582 (tag: linux-nvidia-adv-6.8.0-1003.3) UBUNTU: linux-nvidia-adv-6.8.0-1003.3

**Pull request closed without merging**
